// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzrzWQ8LX1lYfJsXCNXOPuBXEWMmXpANg',
    appId: '1:830746835435:web:d811924578ccd70d5d41ae',
    messagingSenderId: '830746835435',
    projectId: 'evently-481c0',
    authDomain: 'evently-481c0.firebaseapp.com',
    storageBucket: 'evently-481c0.firebasestorage.app',
    measurementId: 'G-PR9QHW48VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALu0OxFK4AqEhSVllH0CBra-WfbRu3S_s',
    appId: '1:830746835435:android:209c64886050976c5d41ae',
    messagingSenderId: '830746835435',
    projectId: 'evently-481c0',
    storageBucket: 'evently-481c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgWNvO7ub9Aov_YQj5qLmnZqiTiVZTBJw',
    appId: '1:830746835435:ios:4cc26331b71796255d41ae',
    messagingSenderId: '830746835435',
    projectId: 'evently-481c0',
    storageBucket: 'evently-481c0.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgWNvO7ub9Aov_YQj5qLmnZqiTiVZTBJw',
    appId: '1:830746835435:ios:4cc26331b71796255d41ae',
    messagingSenderId: '830746835435',
    projectId: 'evently-481c0',
    storageBucket: 'evently-481c0.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzrzWQ8LX1lYfJsXCNXOPuBXEWMmXpANg',
    appId: '1:830746835435:web:8cb26a75db10cc0d5d41ae',
    messagingSenderId: '830746835435',
    projectId: 'evently-481c0',
    authDomain: 'evently-481c0.firebaseapp.com',
    storageBucket: 'evently-481c0.firebasestorage.app',
    measurementId: 'G-2WTS8SF8CB',
  );
}
